### PR TITLE
#235: make body shorten for 50x errors in `Fbe::Middleware::Formatter`

### LINKED ISSUE #235: 50x mistakes from GitHub API
Sometimes GitHub API fails with 50x errors. For example: https://github.com/cqfn/aibolit/actions/runs/16046107982/job/45277749860

We should fail gracefully on our side. `Fbe.octo` must parse the messages GitHub delivers in the HTTP headers and raise a proper exception message (not the one we see currently in the log) -- it's ugly.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #235 

## Summary by CodeRabbit

* **New Features**
  * Enhanced error logging for server responses with status 500 or higher and text-based content, including detailed request and response information with truncated response bodies for readability.

* **Tests**
  * Added tests to verify that long text response bodies in error logs are truncated appropriately.

### CODE REVIEW

**Comment by Yegorov** [comment]
@yegor256 please check

File: lib/fbe/middleware/formatter.rb [hunk 1]
```diff
@@ -105,4 +120,16 @@ def dump_headers(headers)
...
     headers.map { |k, v| "#{k}: #{v.inspect}" }.join("\n")
   end
+
+  # Truncates text if it is longer than a specified :length by appending :omission
+  #
+  # @param [String, nil] txt The text to truncate
+  # @param [Integer] length The number of characters to keep
+  # @param [String] omission The string that will be added to the end as an omission
+  # @return [String] The truncated text, or an empty string if input was nil
+  def truncate(txt, length: 100, omission: '...')
```
Comment (yegor256) [inline lib/fbe/middleware/formatter.rb:130]: @Yegorov you can use this gem instead: https://github.com/yegor256/ellipsized

Comment (Yegorov) [reply lib/fbe/middleware/formatter.rb]: @yegor256 exactly, thanks!

**Comment by Yegorov** [comment]
@yegor256 please check

File: lib/fbe/middleware/formatter.rb [hunk 2]
```diff
@@ -5,6 +5,7 @@
 
 require 'faraday'
 require 'faraday/logging/formatter'
+require 'ellipsized'
```
[the remark this answers is not in the document]
Comment (Yegorov) [reply lib/fbe/middleware/formatter.rb]: @yegor256 of course, fixed.

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by 0crat** [comment]
@yegorov Great work on your contribution! 🌟 You've earned +4 points, bringing your total to [+170](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). While we had to adjust for the missing code review, we appreciate your effort. [Keep the momentum going](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) and remember to include code reviews in future submissions for maximum impact!
