### PR TITLE
#230: add and fix test cases, add ignores option for `Fbe::Middleware::Trace`

### LINKED ISSUE #230: `Fbe.octo` doesn't cache all possible requests (duplicates are visible)
See [this log](https://github.com/zerocracy/judges-action/actions/runs/15967453312/job/45030825046):

```
GitHub API trace (139 URLs vs 1587 requests, 4919 quota left):
  /rate_limit: 16 (3s723ms)
  /repos/zerocracy/baza.rb: 3 (1s023ms)
  /user/526301: 3 (553ms)
  /user/29139614: 2 (436ms)
  /repos/zerocracy/fbe: 2 (681ms)
github-events completed in 2m19s
👍 The 'github-events' judge 486i/4d/6117a out of 8219 facts in 2m19s

👉 Running erase-repository (#1) at judges/erase-repository/ (2m20s already)...
Found [75](https://github.com/zerocracy/judges-action/actions/runs/15967453312/job/45030825046#step:5:76)63/8219 fact(s) by '(and (eq where 'github') (exists repository) (not (exists stale)))' in 9s394ms (slow!)
Txn #49112384 touched 0i/0d/0a in 9s486ms (slow!)
GitHub API trace (9 URLs vs 10 requests, 4909 quota left):
```

We've made three requests to the `/repos/zerocracy/baza.rb` URL and two requests to the `/user/526301` URL. Why didn't we cache the first one and didn't take others from the cache?

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #230

## Summary by CodeRabbit

* **New Features**
  * Added the ability to ignore specific cached HTTP responses in trace logs, improving trace clarity by filtering out selected cache statuses.

* **Bug Fixes**
  * Enhanced trace recording to better distinguish between real network requests and cached responses.
  * Reordered middleware to ensure proper handling of caching and tracing.

* **Tests**
  * Introduced new and updated tests to verify correct trace behavior when HTTP caching is involved, ensuring only real network requests are logged.
  * Added tests to confirm middleware order and caching behavior in API client.

### CODE REVIEW

**Comment by Yegorov** [comment]
@yegor256 please check

File: lib/fbe/octo.rb [hunk 1]
```diff
@@ -109,7 +109,7 @@ def Fbe.octo(options: $options, global: $global, loog: $loog)
             builder.use(Octokit::Response::RaiseError)
             builder.use(Faraday::Response::Logger, loog, formatter: Fbe::Middleware::Formatter)
             builder.use(Fbe::Middleware::RateLimit)
-            builder.use(Fbe::Middleware::Trace, trace)
+            builder.use(Fbe::Middleware::Trace, trace, ignores: [:fresh])
```
Comment (yegor256) [inline lib/fbe/octo.rb:112]: @Yegorov is it a typo? shouldn't it be `:http_cache_trace`?

Comment (Yegorov) [reply lib/fbe/octo.rb:112]: @yegor256 ok, i add test.

**Comment by Yegorov** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegorov Thanks for your contribution! 🚀 You've earned +8 points: +16 base, +7 for 155 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -16 for no code review. Great job on the code volume, but remember to get reviews next time for maximum points. Your balance is now [+173](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for those bonus points by following our [policy](https://www.yegor256.com/2018/03/06/speed-vs-quality.html)!
