### PR TITLE
#205: add version for sqlite cache store

### LINKED ISSUE #205: sqlite cache is not versioned
Currently, if sqlite cache is created by one version of Fbe and is opened by another version of Fbe, it may not work (for a number of reasons). Let's introduce a check: if we open a DB and its version (stored in some supplementary table) is not equal to `Fbe::VERSION`, we simply destroy it and recreate from scratch.

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #205 

## Summary by CodeRabbit

- **New Features**
  - Introduced version tracking in the SQLite cache store, allowing detection and handling of version mismatches.
  - Cache is now automatically cleared if a version difference is detected.

- **Bug Fixes**
  - Improved cache consistency by ensuring outdated cache data is removed when the application version changes.

- **Tests**
  - Added and updated tests to verify version tracking, cache clearing, and error handling for invalid version inputs.
  - Added tests to confirm cache refresh behavior when using different application versions.

- **Chores**
  - Added new test dependencies to support enhanced testing capabilities.

### CODE REVIEW

**Comment by Yegorov** [comment]
@yegor256 please check.

File: lib/fbe/middleware/sqlite_store.rb [hunk 1]
```diff
@@ -16,11 +16,13 @@
 class Fbe::Middleware::SqliteStore
   attr_reader :path
 
-  def initialize(path)
+  def initialize(path, fbe_version)
```
Comment (yegor256) [inline lib/fbe/middleware/sqlite_store.rb:19]: @Yegorov try to avoid compound/composite variable names: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: lib/fbe/octo.rb [hunk 2]
```diff
@@ -77,12 +77,19 @@ def Fbe.octo(options: $options, global: $global, loog: $loog)
...
             )
             if options.sqlite_cache
-              store = Fbe::Middleware::SqliteStore.new(options.sqlite_cache)
+              store = Fbe::Middleware::SqliteStore.new(options.sqlite_cache, Fbe::VERSION)
               loog.info(
                 "Using HTTP cache in SQLite file: #{store.path} (" \
                 "#{File.exist?(store.path) ? "#{File.size(store.path)} bytes" : 'file is absent'}" \
                 ')'
               )
+              if store.different_versions?
```
Comment (yegor256) [inline lib/fbe/octo.rb:86]: @Yegorov it seems that this functionality belongs to `SqliteStore` class, not to its clients. The store should decide when and how its content should be cleaned up.

**Comment by yegor256** [comment]
@Yegorov looks like a good start! See a few comments above

File: lib/fbe/middleware/sqlite_store.rb [hunk 3]
```diff
@@ -49,7 +51,11 @@ def write(key, value)
   end
 
   def clear
-    perform { _1.execute 'DELETE FROM cache;' }
+    perform do |t|
+      t.execute 'DELETE FROM cache;'
+      t.execute "UPDATE meta SET value = ? WHERE key = 'version';", [@version]
+    end
+    @db.execute 'VACUUM;'
   end
```
[the remark this answers is not in the document]
Comment (Yegorov) [reply lib/fbe/middleware/sqlite_store.rb:59]: @coderabbitai this aproach not working, i get error in test: `SQLite3::SQLException: cannot VACUUM from within a transaction`

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Yegorov you see how much better the design is now?

**Comment by yegor256** [comment]
@rultor merge

**Comment by Yegorov** [comment]
> @Yegorov you see how much better the design is now?

@yegor256 yes, there really is something to it, thanks!
